name: tapped_test_toolkit
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.16.0"

dependencies:
  args: ^2.5.0
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  # formatting the time of some jobs
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  tapped_lints:
    git:
      url: https://github.com/tappeddev/tapped_lints.git
      ref: master

flutter:
